PharmacyManagementSystem/Controllers/Inventory/MedicineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PharmacyManagementSystem.Models;

namespace PharmacyManagementSystem.Controllers.Inventory
{
    public class MedicineController : Controller
    {
        private PMSEntities db = new PMSEntities();

        //
        // GET: /Medicine/

        public ActionResult Index(string searchBy, string search)
        {
            if (searchBy == "Medicine_Name")
            {
                return View(db.Medicine_Information.Where(x => x.Medicine_Name.Contains(search) || search == null).ToList());
            }
            else if (searchBy == "Category")
            {
                return View(db.Medicine_Information.Where(x => x.Category.Contains(search) || search == null).ToList());
            }
            else if (searchBy == "Genric_Name")
            {
                return View(db.Medicine_Information.Where(x => x.Drug_Generic_name.Genric_Name.Contains(search) || search == null).ToList());
            }
            else
            {
                return View(db.Medicine_Information.Where(x => x.Manufacturer.Manufacturer_Name.Contains(search) || search == null).ToList());
            }

            //var medicine_information = db.Medicine_Information.Include(m => m.Drug_Generic_name).Include(m => m.Manufacturer);
            //return View(medicine_information.ToList());
        }

  

        //
        // GET: /Medicine/Details/5

        public ActionResult Details(int id = 0)
        {
            Medicine_Information medicine_information = db.Medicine_Information.Find(id);
            if (medicine_information == null)
            {
                return HttpNotFound();
            }
            return View(medicine_information);
        }

        //
        // GET: /Medicine/Create

        public ActionResult Create()
        {
            ViewBag.Generic_ID = new SelectList(db.Drug_Generic_name, "ID", "Genric_Name");
            ViewBag.Manufacturer_ID = new SelectList(db.Manufacturers, "ID", "Manufacturer_Name");
            return View();
        }

        //
        // POST: /Medicine/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Medicine_Information medicine_information)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Medicine_Information.Add(medicine_information);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    ModelState.AddModelError("Error", "Generic Name Already Assigned");
                }
            }

            ViewBag.Generic_ID = new SelectList(db.Drug_Generic_name, "ID", "Genric_Name", medicine_information.Generic_ID);
            ViewBag.Manufacturer_ID = new SelectList(db.Manufacturers, "ID", "Manufacturer_Name", medicine_information.Manufacturer_ID);
            return View(medicine_information);
        }

        //
        // GET: /Medicine/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Medicine_Information medicine_information = db.Medicine_Information.Find(id);
            if (medicine_information == null)
            {
                return HttpNotFound();
            }
            //ViewBag.Generic_ID = new SelectList(db.Drug_Generic_name, "ID", "Genric_Name", medicine_information.Generic_ID);
            ViewBag.Manufacturer_ID = new SelectList(db.Manufacturers, "ID", "Manufacturer_Name", medicine_information.Manufacturer_ID);
            return View(medicine_information);
        }

        //
        // POST: /Medicine/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Medicine_Information medicine_information)
        {
            if (ModelState.IsValid)
            {
                db.Medicine_Information.Attach(medicine_information);
                db.Entry(medicine_information).Property(r => r.Medicine_Name).IsModified = true;
                db.Entry(medicine_information).Property(r => r.Category).IsModified = true;
                db.Entry(medicine_information).Property(r => r.Manufacturer_ID).IsModified = true;
               // db.Entry(medicine_information).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(medicine_information);
            }
             //ViewBag.Generic_ID = new SelectList(db.Drug_Generic_name, "ID", "Genric_Name", medicine_information.Generic_ID);
           // ViewBag.Manufacturer_ID = new SelectList(db.Manufacturers, "ID", "Manufacturer_Name", medicine_information.Manufacturer_ID);
           
        }

        //
        // GET: /Medicine/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Medicine_Information medicine_information = db.Medicine_Information.Find(id);
            if (medicine_information == null)
            {
                return HttpNotFound();
            }
            return View(medicine_information);
        }

        //
        // POST: /Medicine/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Medicine_Information medicine_information = db.Medicine_Information.Find(id);
            db.Medicine_Information.Remove(medicine_information);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PharmacyManagementSystem/Views/Medicine/Create.cshtml
@model PharmacyManagementSystem.Models.Medicine_Information

@{
    ViewBag.Title = "Create";
    if (Session["Usertype"] != null)
    {
        if (Session["Usertype"].ToString() == "Admin")
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
        else
        {
            Response.Write("<script>alert('Access Denied') ; window.location.href='/Medicine/Index'</script>");
        }
    }
    else
    {
        Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/Login/Login'</script>");
    }
}

<h2>&nbspCreate Medicine Information</h2>

<hr width="99%">

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <table cellspacing="40">

        <tr align="right">
            <td>Medicine Name</td>
            <td>
                @Html.TextBoxFor(model => model.Medicine_Name, new { style = "width:300px; height:25px; font-size: 16px;" })
            </td>
            <td align="left">@Html.ValidationMessageFor(model => model.Medicine_Name, null, new { style = "color:red" })</td>
        </tr>
        
        <tr align="right">
            <td>Category</td>
            <td>
                @Html.DropDownList("Category", new List<SelectListItem>
                {
                    new SelectListItem{ Text="Tablet", Value = "Tablet" },
                    new SelectListItem{ Text="Capsule", Value = "Capsule" },
                    new SelectListItem{ Text="Syrup", Value = "Syrup" },
                 }, "Select Category", new { style = "width:300px; height:30px; font-size: 16px;" })
                
            </td>
            <td align="left">@Html.ValidationMessageFor(model => model.Category, null, new { style = "color:red" })</td>
        </tr>


        <tr align="right">
            <td>Generic Name</td>
            <td>
              @Html.DropDownList("Generic_ID", null, "Select Generic Name", new { style = "width:300px; height:30px; font-size: 16px;" })
            </td>
            <td align="left">@Html.ValidationMessageFor(model => model.Generic_ID, null, new { style = "color:red" })</td>
            <td align="left">@Html.ValidationMessage("Error", new { style = "color:red" })</td>
        </tr>



        <tr align="right">
            <td>Manufacturer Name</td>
            <td>
                @Html.DropDownList("Manufacturer_ID", null, "Select Manufacturer", new { style = "width:300px; height:30px; font-size: 16px;" })
            </td>
            <td align="left">@Html.ValidationMessageFor(model => model.Manufacturer_ID, null, new { style = "color:red" })</td>
        </tr>



        <tr>
            <td></td>
            <td><input type="submit" value="Create" style="width:100px; height:35px;" /></td>
        </tr>
    </table>

}

<div>
    &nbsp  @Html.ActionLink("Back to List", "Index")
</div>
<br />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PharmacyManagementSystem/Views/Medicine/Delete.cshtml
@model PharmacyManagementSystem.Models.Medicine_Information

@{
    ViewBag.Title = "Delete";
    if (Session["Usertype"] != null)
    {
        if (Session["Usertype"].ToString() == "Admin")
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
        else
        {
            Response.Write("<script>alert('Access Denied') ; window.location.href='/Medicine/Index'</script>");
        }
    }
    else
    {
        Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/Login/Login'</script>");
    }
}

<div>
    <h2>&nbspDelete Medicine Details</h2>

    <hr width="99%">

    <h3>&nbsp&nbspAre you sure you want to delete this?</h3>
</div>

<table border="1" cellpadding="10" style="margin-top:30px; margin-left:10px; margin-right:10px;margin-bottom:30px">

    <tr>
        <td>Medicine Name</td>
        <td> @Html.DisplayFor(model => model.Medicine_Name)</td>
    </tr>

    <tr>
        <td>Category</td>
        <td> @Html.DisplayFor(model => model.Category)</td>
    </tr>
    <tr>
        <td>Generic Name</td>
        <td> @Html.DisplayFor(model => model.Drug_Generic_name.Genric_Name)</td>
    </tr>
    <tr>
        <td>Manufacturer</td>
        <td> @Html.DisplayFor(model => model.Manufacturer.Manufacturer_Name)</td>
    </tr>

</table>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <input type="submit" value="Delete" style=" height:29px; width:100px; margin:0px 10px 30px 10px " />
}

<div>
    &nbsp @Html.ActionLink("Back to List", "Index")
</div>

<br />

PharmacyManagementSystem/Views/Medicine/Details.cshtml
@model PharmacyManagementSystem.Models.Medicine_Information

@{
    ViewBag.Title = "Details";
    if (Session["Usertype"] != null)
    {
        if (Session["Usertype"].ToString() == "Admin")
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_LayoutStaff.cshtml";
        }
    }
    else
    {
        Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/Login/Login'</script>");
    }
}


<h2>&nbspMedicine Details</h2>

<hr width="99%">


<table border="1" cellpadding="10" style="margin-top:30px; margin-left:10px; margin-right:10px;margin-bottom:30px">

    <tr>
        <td>Medicine Name</td>
        <td> @Html.DisplayFor(model => model.Medicine_Name)</td>
    </tr>

    <tr>
        <td>Category</td>
        <td> @Html.DisplayFor(model => model.Category)</td>
    </tr>
    <tr>
        <td>Generic Name</td>
        <td> @Html.DisplayFor(model => model.Drug_Generic_name.Genric_Name)</td>
    </tr>
    <tr>
        <td>Manufacturer</td>
        <td> @Html.DisplayFor(model => model.Manufacturer.Manufacturer_Name)</td>
    </tr>

</table>

<p>
    &nbsp&nbsp  @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PharmacyManagementSystem/Views/Medicine/Edit.cshtml
@model PharmacyManagementSystem.Models.Medicine_Information

@{
    ViewBag.Title = "Edit";
    if (Session["Usertype"] != null)
    {
        if (Session["Usertype"].ToString() == "Admin")
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
        else
        {
            Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/Medicine/Index'</script>");
        }
    }
    else
    {
        Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/Login/Login'</script>");
    }
}

<h2>&nbspEdit Medicine Information</h2>

<hr width="99%">

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


    <table cellspacing="40">

        @Html.HiddenFor(model => model.ID)
        <tr align="right">
            <td>Medicine Name</td>
            <td>
                @Html.TextBoxFor(model => model.Medicine_Name, new { style = "width:300px; height:25px; font-size: 16px;" })
            </td>
            <td align="left">@Html.ValidationMessageFor(model => model.Medicine_Name, null, new { style = "color:red" })</td>
        </tr>

        <tr align="right">
            <td>Category</td>
            <td>
                @Html.DropDownList("Category", new List<SelectListItem>
                {
                    new SelectListItem{ Text="Tablet", Value = "Tablet" },
                    new SelectListItem{ Text="Capsule", Value = "Capsule" },
                    new SelectListItem{ Text="Syrup", Value = "Syrup" },
                 }, "Select Category", new { style = "width:300px; height:30px; font-size: 16px;" })

            </td>
            <td align="left">@Html.ValidationMessageFor(model => model.Category, null, new { style = "color:red" })</td>
        </tr>

        @*<tr align="right">
            <td>Generic Name</td>
            <td>
                @Html.DropDownList("Generic_ID", null, "Select Generic Name", new { style = "width:300px; height:30px; font-size: 16px;" })

            </td>
        </tr>*@

        <tr align="right">
            <td>Manufacturer Name</td>
            <td>
                @Html.DropDownList("Manufacturer_ID", null, "Select Manufacturer", new { style = "width:300px; height:30px; font-size: 16px;" })
            </td>
            <td align="left">@Html.ValidationMessageFor(model => model.Manufacturer_ID, null, new { style = "color:red" })</td>
        </tr>


        <tr>
            <td></td>
            <td><input type="submit" value="Update" style="width:100px; height:35px;" /></td>
        </tr>
    </table>

    
    
}

<div>
    &nbsp  @Html.ActionLink("Back to List", "Index")
</div>
<br />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PharmacyManagementSystem/Views/Medicine/Index.cshtml
@model IEnumerable<PharmacyManagementSystem.Models.Medicine_Information>

@{
    ViewBag.Title = "Index";
    if (Session["Usertype"] != null)
    {
        if (Session["Usertype"].ToString() == "Admin")
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_LayoutStaff.cshtml";
        }
    }
    else
    {
        Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/Login/Login'</script>");
    }
}

<h2>&nbspList of Medicine Information</h2>

<hr width="99%">

<p>
    &nbsp&nbsp
    @Html.ActionLink("Create New", "Create")
</p>

<p>
    @using (@Html.BeginForm("Index", "Medicine", FormMethod.Get))
    {
        <b>&nbsp&nbspSearch By:</b>
        @Html.RadioButton("searchBy", "Medicine_Name", true) <text>Medicine</text>
        @Html.RadioButton("searchBy", "Category") <text>Category</text>
        @Html.RadioButton("searchBy", "Genric_Name") <text>Generic Name</text>
        @Html.RadioButton("searchBy", "Manufacturer_Name") <text>Manufacturer</text><br /><br />
        @Html.TextBox("Search", null, new { @style = " height:22px; width:200px;margin: 0px 5px 0px 10px" })    <input type="submit" value="Search" style=" height:29px; width:100px " />
    }
</p>

<table border="1" cellpadding="10" style="margin-top:10px; margin-left:10px;">
    <tr>
        <th>
            Medicine Name
        </th>
        <th>
            Category
        </th>
        <th>
            Generic Name
        </th>
        <th>
            Manufacturer
        </th>
        <th>
            Action
        </th>
    </tr>
@if (Model.Count() == 0)
    {
    <tr>
        <td colspan="6" align="center">
            No records match search criteria
        </td>
    </tr>
    }

    else
    {
       foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Medicine_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Drug_Generic_name.Genric_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Manufacturer.Manufacturer_Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }
        }
</table>

<br />
<br />
<div>
    &nbsp   @Html.ActionLink("Back to Inventory", "Inventory", "Inventory")
</div>
<br />