PharmacyManagementSystem/Controllers/Purchase/PurchaseHistoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PharmacyManagementSystem.Models;
using PagedList;
using PagedList.Mvc;
using System.Net;
using System.Data.Entity.Validation;
using System.Diagnostics;

namespace PharmacyManagementSystem
{
    public class PurchaseHistoryController : Controller
    {
        private PMSEntities db = new PMSEntities();

        //
        // GET: /PurchaseHistory/

        public ActionResult Index(string searchBy, string search)
        {
            var purchases = db.Purchases.Include(p => p.Supplier);

            if (searchBy == "Purchase_ID")
            {
                return View(db.Purchases.Where(x => x.Purchase_ID.Contains(search) || search == null).ToList());
            }
            else
            {
                return View(db.Purchases.Where(x => x.Supplier.Supplier_Name.Contains(search) || search == null).ToList());
            }

            //return View(purchases.ToList());
        }

        //
        // GET: /PurchaseHistory/Details/5

        public ActionResult Details(string id)
        {
             var purchasedItem = (from n in db.Batches
                            where n.Purchase_ID == id
                                  select n).ToList();
             return View(purchasedItem);  
        }

        //
        // GET: /PurchaseHistory/Edit/5

        public ActionResult Edit(string id = null)
        {
            Purchase purchase = db.Purchases.Find(id);
            if (purchase == null)
            {
                return HttpNotFound();
            }
            ViewBag.Supplier_ID = new SelectList(db.Suppliers, "ID", "Supplier_Name", purchase.Supplier_ID);
            return View(purchase);
        }

        //
        // POST: /PurchaseHistory/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Purchase purchase)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Purchases.Attach(purchase);
                    db.Entry(purchase).Property(r => r.IsPaid).IsModified = true;
                    db.Entry(purchase).Property(r => r.Description).IsModified = true;
                    //db.Entry(purchase).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            Trace.TraceInformation("Property: {0} Error: {1}",
                                                    validationError.PropertyName,
                                                    validationError.ErrorMessage);
                        }
                    }
                }
            }
            ViewBag.Supplier_ID = new SelectList(db.Suppliers, "ID", "Supplier_Name", purchase.Supplier_ID);
            return View(purchase);
        }

        //
        // GET: /PurchaseHistory/Delete/5

        public ActionResult Delete(string id = null)
        {
            Purchase purchase = db.Purchases.Find(id);
            if (purchase == null)
            {
                return HttpNotFound();
            }
            return View(purchase);
        }

        //
        // POST: /PurchaseHistory/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Purchase purchase = db.Purchases.Find(id);
            db.Purchases.Remove(purchase);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PharmacyManagementSystem/Views/PurchaseHistory/Details.cshtml
@model IEnumerable<PharmacyManagementSystem.Models.Batch>
@*@model PharmacyManagementSystem.Models.Batch*@

@{
    ViewBag.Title = "Details";
    if (Session["Usertype"] != null)
    {
        if (Session["Usertype"].ToString() == "Admin")
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_LayoutStaff.cshtml";
        }
    }
    else
    {
        Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/Login/Login'</script>");
    }
}

<h2>&nbspPurchase Details</h2>

<hr width="99%">



<table align="center">

    <tr>
        <td style="font-weight:bold;font-size:20px;">Purchase ID : </td>
        <td></td>
        <td align="center" style="font-size:20px;">@Html.DisplayFor(model => model.First().Purchase_ID)</td>
    </tr>    
    <tr>
        <td style="font-weight:bold;font-size:20px;">Date : </td>
        <td></td>
        <td align="center" style="font-size:20px;">@Html.DisplayFor(model => model.First().Purchase.Entry_Date)</td>
    </tr>
    <tr>
        <td style="font-weight:bold;font-size:20px;">Description : </td>
        <td></td>
        <td align="center" style="font-size:20px;">@Html.DisplayFor(model => model.First().Purchase.Description)</td>
    </tr>
        
</table>

<br />



    <div align="center">

        <table border="1" cellpadding="10" style="margin-top:10px; margin-left:10px;">
            <tr>
                <th>
                    Purhase ID
                </th>
                <th>
                    Medicine Name
                </th>
                <th>
                    Batch ID
                </th>
                <th>
                    Quantity
                </th>
                <th>
                    Cost Price
                </th>
                <th>
                    Sell Price
                </th>
                <th>
                    Production Date
                </th>
                <th>
                    Expire Date
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Purchase_ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Medicine_Information.Medicine_Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Batch_ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cost_Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sell_Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Production_Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Expire_Date)
                    </td>
                </tr>
            }

        </table>

    </div>

<p>
    &nbsp&nbsp  @Html.ActionLink("Back to List", "Index")
</p>

PharmacyManagementSystem/Views/PurchaseHistory/Edit.cshtml
@model PharmacyManagementSystem.Models.Purchase

@{
    ViewBag.Title = "Edit";
    if (Session["Usertype"] != null)
    {
        if (Session["Usertype"].ToString() == "Admin")
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
        else
        {
            Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/PurchaseHistory/Index'</script>");
        }
    }
    else
    {
        Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/Login/Login'</script>");
    }
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <table cellspacing="40">

        <tr align="right">
            <td>Purchase ID</td>
            <td>
                @Html.TextBoxFor(model => model.Purchase_ID, new { style = "width:300px; height:25px; font-size: 16px;", @readonly = "readonly" })
            </td>
        </tr>
        <tr align="right">
            <td>Discount(%)</td>
            <td>
                @Html.TextBoxFor(model => model.Discount, new { style = "width:300px; height:25px; font-size: 16px;", @readonly = "readonly" })
            </td>
        </tr>
        <tr align="right">
            <td>Description</td>
            <td>
                @Html.TextAreaFor(model => model.Description, new { style = "width:300px; height:100px; font-size: 16px;" })
            </td>
        </tr>
        <tr align="right">
            <td>IsPaid</td>
            <td align="left">
                @Html.RadioButtonFor(model => model.IsPaid, "Paid") Paid
                @Html.RadioButtonFor(model => model.IsPaid, "Credit") Credit
            </td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Update" style="width:100px; height:35px;" /></td>
        </tr>

    </table>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PharmacyManagementSystem/Views/PurchaseHistory/Index.cshtml
@model IEnumerable<PharmacyManagementSystem.Models.Purchase>

@{
    ViewBag.Title = "Purchase History";

    if (Session["Usertype"] != null)
    {
        if (Session["Usertype"].ToString() == "Admin")
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_LayoutStaff.cshtml";
        }
    }
    else
    {
        Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/Login/Login'</script>");
    }
}

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css"/>

<h2>&nbspList of Purchases</h2>

<hr width="99%">

<p>
    @using (@Html.BeginForm("Index", "PurchaseHistory", FormMethod.Get))
    {
        <b>&nbsp&nbspSearch By:</b>
        @Html.RadioButton("searchBy", "Purchase_ID", true) <text>Purchase ID</text>
        @Html.RadioButton("searchBy", "Supplier_Name") <text>Supplier Name</text><br /><br />
        @Html.TextBox("search", null, new { @style = " height:22px; width:200px;margin: 0px 5px 0px 10px" })    <input type="submit" value="Search" style=" height:29px; width:100px " />
    }
</p>


<table border="1" cellpadding="10" style="margin-top:10px; margin-left:10px;">
    <tr>
        <th>
            Purhase ID
        </th>
        <th>
            Supplier Name
        </th>
        <th>
            Entry Date
        </th>
        <th>
            Amount
        </th>
        <th>
            Discount(%)
        </th>
        <th>
            Discount Amount
        </th>
        <th>
            Grand Total
        </th>
        <th>
            IsPaid
        </th>
        <th>Action</th>
    </tr>

    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="9" align="center">
                No records match search criteria
            </td>
        </tr>
    }

    else { 
        
    foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Purchase_ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Supplier.Supplier_Name)
            </td>
            <td>
                @Convert.ToString(string.Format("{0:dd-MM-yyyy}", item.Entry_Date))
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Discount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Discount_Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grand_Total)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsPaid)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Purchase_ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.Purchase_ID }) 
            </td>
        </tr>
        }
    }

</table>